export interface RestaurantTypeData {
  slug: string;
  name: string;
  nameFull: string;
  tagline: string;
  targetMargin: number;
  foodCostPct: number;
  marginRange: string;
  avgCheckSize: string;
  keyChallenge: string;
  dishes: { name: string; cost: number; price: number; margin: number }[];
  tips: { title: string; desc: string }[];
  faqs: { q: string; a: string }[];
}

export const RESTAURANT_TYPES: Record<string, RestaurantTypeData> = {
  "fine-dining": {
    slug: "fine-dining",
    name: "Fine Dining",
    nameFull: "Fine Dining Restaurant",
    tagline: "Premium pricing strategy for upscale restaurants",
    targetMargin: 75,
    foodCostPct: 25,
    marginRange: "72–80%",
    avgCheckSize: "$80–$150 per person",
    keyChallenge: "Justifying premium prices with quality, presentation, and experience",
    dishes: [
      { name: "Pan-Seared Duck Breast", cost: 14.5, price: 58, margin: 75 },
      { name: "Wagyu Beef Tenderloin", cost: 28, price: 110, margin: 75 },
      { name: "Lobster Bisque", cost: 8.5, price: 34, margin: 75 },
      { name: "Truffle Risotto", cost: 11, price: 44, margin: 75 },
      { name: "Chocolate Fondant", cost: 3.5, price: 18, margin: 81 },
    ],
    tips: [
      { title: "Price for experience, not just food", desc: "Fine dining guests pay for ambiance, service, and presentation. Your ingredient cost can go up to 28% without hurting profitability." },
      { title: "Use psychological pricing", desc: "Drop the dollar sign on menus — studies show guests spend 8–12% more without the $ symbol. Use '58' instead of '$58.00'." },
      { title: "Engineer your menu sections", desc: "Place your highest-margin items in the top-right of each section — where eyes naturally land first on a printed menu." },
      { title: "Build in seasonal flexibility", desc: "Price proteins based on seasonal availability. A spring lamb dish priced at 72% margin can be repriced quarterly as costs fluctuate." },
    ],
    faqs: [
      { q: "What food cost percentage should fine dining restaurants target?", a: "Fine dining restaurants typically target 25–30% food cost (70–75% gross margin). Higher-end establishments can sustain up to 32% because premium pricing covers the gap. The key is total prime cost (food + labor) staying below 60% of revenue." },
      { q: "How do I price a tasting menu?", a: "Calculate the total ingredient cost of all courses, then price the tasting menu at 3.5–4x that cost. For example, if 7 courses cost $45 in ingredients, price the menu at $160–$180. Include wine pairing at 40–50% additional markup." },
      { q: "Should fine dining prices include service?", a: "In the US, most fine dining adds 18–22% gratuity automatically. In European-style service-included models, build a 15% service charge into menu prices and communicate it clearly." },
    ],
  },

  "fast-casual": {
    slug: "fast-casual",
    name: "Fast Casual",
    nameFull: "Fast Casual Restaurant",
    tagline: "Efficient menu pricing for fast casual concepts",
    targetMargin: 70,
    foodCostPct: 30,
    marginRange: "67–73%",
    avgCheckSize: "$12–$18 per person",
    keyChallenge: "Competing on value while maintaining healthy margins at high volume",
    dishes: [
      { name: "Build-Your-Own Bowl", cost: 3.8, price: 13, margin: 71 },
      { name: "Signature Burger", cost: 4.2, price: 14, margin: 70 },
      { name: "Chicken Sandwich", cost: 3.5, price: 12, margin: 71 },
      { name: "Street Tacos (3pc)", cost: 2.8, price: 10, margin: 72 },
      { name: "Fresh-Pressed Juice", cost: 1.5, price: 6, margin: 75 },
    ],
    tips: [
      { title: "Bundle to boost average ticket", desc: "A combo (entrée + drink + side) priced at $16 with 68% margin beats three separate items at 72% margin if it increases attachment rate. Bundles increase revenue per transaction by 20–35%." },
      { title: "Price drinks and sides high", desc: "Beverages typically carry 75–85% margins. A $4 fountain drink with $0.40 cost is your most profitable menu item. Sides like fries at $3.50 with 78% margin anchor your profit." },
      { title: "Streamline modifiers", desc: "Every customization option adds labor cost. Limit protein upgrades to +$2–$3 and premium add-ons to +$1–$2. Price upgrades at 80%+ margin." },
      { title: "Monitor food cost weekly", desc: "At fast casual volumes, a 2% food cost increase equals $20K–$40K less profit annually. Use MenuPricer to recalculate prices whenever supplier costs change." },
    ],
    faqs: [
      { q: "What is the ideal food cost for fast casual restaurants?", a: "Fast casual restaurants typically target 28–32% food cost (68–72% gross margin). Chains like Chipotle run at 29–31%. The higher volume compared to fine dining compensates for the tighter margins per item." },
      { q: "How do fast casual restaurants price delivery orders?", a: "Add 15–20% to your in-restaurant prices for delivery to offset platform commissions (15–30% from DoorDash, Uber Eats, etc.). Many fast casual operators maintain separate delivery menus priced 18–22% higher than in-store." },
      { q: "How often should fast casual menus be repriced?", a: "Review food costs monthly and adjust prices quarterly. With volatile protein and produce costs, fast casual restaurants that don't adjust prices for 6+ months often see food cost creep from 30% to 35–37%, significantly eroding margins." },
    ],
  },

  "food-truck": {
    slug: "food-truck",
    name: "Food Truck",
    nameFull: "Food Truck",
    tagline: "Lean menu pricing strategy for food trucks",
    targetMargin: 68,
    foodCostPct: 32,
    marginRange: "65–72%",
    avgCheckSize: "$10–$16 per person",
    keyChallenge: "Covering high operational costs (fuel, permits, commissary) with a small, fast-moving menu",
    dishes: [
      { name: "Signature Tacos (2pc)", cost: 2.5, price: 8, margin: 69 },
      { name: "BBQ Brisket Sandwich", cost: 4.5, price: 14, margin: 68 },
      { name: "Loaded Fries", cost: 1.8, price: 7, margin: 74 },
      { name: "Korean Fried Chicken Bowl", cost: 3.8, price: 12, margin: 68 },
      { name: "Fresh Lemonade", cost: 0.6, price: 4, margin: 85 },
    ],
    tips: [
      { title: "Keep your menu to 6–8 items max", desc: "A tight menu reduces waste, prep time, and inventory costs. Every extra menu item adds 3–5% to your food cost through spoilage and over-ordering." },
      { title: "Price for your event premium", desc: "Festival and event pricing can be 20–30% higher than street pricing. A $10 taco at your regular spot becomes $12–$13 at a food festival — guests expect it and pay it." },
      { title: "Track waste ruthlessly", desc: "Food trucks lose 8–12% of revenue to waste on average. Track daily waste per item and cut anything that consistently goes unsold. One cut item can recover 2–3% food cost." },
      { title: "Drinks are your profit anchor", desc: "A $3 can of soda or $4 bottled water at 85–90% margin can subsidize a signature dish you price competitively. Always push drink attachment." },
    ],
    faqs: [
      { q: "How do food trucks calculate menu prices?", a: "Food trucks typically target 28–35% food cost (65–72% gross margin). Apply the formula: Menu Price = Ingredient Cost ÷ (1 − Target Margin). For a dish costing $3.50 at 68% margin: $3.50 ÷ 0.32 = $10.94, round to $11." },
      { q: "How do commissary costs affect food truck pricing?", a: "Commissary kitchen rental ($400–$1,500/month), fuel ($300–$800/month), and permits ($500–$3,000/year) add significant overhead. Factor these into your pricing by targeting food cost no higher than 32%— leaving enough gross margin to cover these fixed costs." },
      { q: "Should food truck prices match nearby restaurants?", a: "Benchmark against nearby quick-service restaurants, not sit-down restaurants. Food truck guests expect street food pricing but understand the premium for specialty, chef-driven concepts. You can charge 10–15% more than a comparable fast food item if your product is differentiated." },
    ],
  },

  "bakery": {
    slug: "bakery",
    name: "Bakery & Café",
    nameFull: "Bakery and Café",
    tagline: "Margin-focused pricing for bakeries and cafés",
    targetMargin: 70,
    foodCostPct: 30,
    marginRange: "68–75%",
    avgCheckSize: "$8–$15 per person",
    keyChallenge: "Managing high labor and ingredient costs while competing on quality and experience",
    dishes: [
      { name: "Sourdough Loaf", cost: 1.8, price: 9, margin: 80 },
      { name: "Croissant", cost: 0.9, price: 4.5, margin: 80 },
      { name: "Specialty Latte", cost: 0.85, price: 5.5, margin: 85 },
      { name: "Custom Cake (per slice)", cost: 2.5, price: 9, margin: 72 },
      { name: "Breakfast Sandwich", cost: 2.8, price: 9.5, margin: 71 },
    ],
    tips: [
      { title: "Price bread by perceived value, not just cost", desc: "A $1.80 sourdough loaf can sell for $9–$12 at a specialty bakery. Customers pay for craft, sourcing story, and quality. Train staff to explain your fermentation process and local grain sourcing." },
      { title: "Coffee is your highest-margin product", desc: "A specialty latte with $0.85 COGS priced at $5.50 delivers 85% gross margin. Push coffee attachment with every baked good sale — a 'coffee + pastry' combo at $8.50 beats both items sold separately." },
      { title: "Custom orders need separate pricing", desc: "Custom cakes and catering orders should target only 65% margin (higher cost, more labor) but require a minimum order of $50–$100 to be worthwhile. Always charge a deposit." },
      { title: "Use end-of-day markdown strategically", desc: "Discount day-old items by 30–40% in the last hour before closing. This reduces waste and brings in price-sensitive customers who become regulars." },
    ],
    faqs: [
      { q: "What is a good profit margin for a bakery?", a: "Bakeries typically target 68–75% gross margin (25–32% food cost). Bread and pastries can achieve 78–85% margin on ingredients alone, but high labor costs (30–35% of revenue for scratch bakeries) eat into net profit. Target net profit of 8–15%." },
      { q: "How do I price custom cakes?", a: "Custom cake pricing formula: (Ingredient cost × 3) + (Hours of labor × $15–$25/hr) + overhead allocation ($5–$15 per cake). A 3-tier wedding cake with $45 in ingredients and 8 hours of labor: ($45 × 3) + (8 × $20) = $295 minimum. Most wedding cakes sell for $400–$800." },
      { q: "Should bakeries charge more at farmers markets?", a: "Yes — add 15–25% for farmers market pricing to cover booth fees ($50–$200/day), extra prep, and transportation. Market customers expect slight premiums and prioritize quality over price." },
    ],
  },

  "pizza": {
    slug: "pizza",
    name: "Pizza Restaurant",
    nameFull: "Pizza Restaurant",
    tagline: "Profit-optimized pricing for pizza restaurants",
    targetMargin: 72,
    foodCostPct: 28,
    marginRange: "70–76%",
    avgCheckSize: "$15–$30 per order",
    keyChallenge: "Balancing low food costs with delivery platform commissions eating into margins",
    dishes: [
      { name: "Margherita Pizza (12\")", cost: 3.2, price: 14, margin: 77 },
      { name: "Pepperoni Pizza (14\")", cost: 4.5, price: 18, margin: 75 },
      { name: "BBQ Chicken Pizza (12\")", cost: 4.8, price: 17, margin: 72 },
      { name: "Garlic Bread", cost: 0.8, price: 5, margin: 84 },
      { name: "2L Soda", cost: 0.9, price: 4.5, margin: 80 },
    ],
    tips: [
      { title: "Size pricing is your biggest lever", desc: "The jump from 12\" to 14\" pizza uses ~36% more dough but charge only 20–25% more. Most guests choose the larger size, boosting revenue per order without proportional cost increase." },
      { title: "Price delivery menus separately", desc: "Set delivery menu prices 18–22% higher than dine-in. With DoorDash/Uber Eats taking 20–30% commission, a $14 pizza nets you $9.80–$11.20. At delivery pricing of $17, you net $11.90–$13.60." },
      { title: "Bundle deals boost average order value", desc: "A family bundle (large pizza + 2 sides + 2L drink) at $32 with 72% margin outperforms 4 separate items. Bundles increase order frequency and average ticket by 25–40%." },
      { title: "Topping pricing strategy", desc: "Price the first 2 toppings 'free' in your base pizza price, then charge $1.50–$2.50 for additional toppings. Specialty toppings (truffle, prosciutto) can command $3–$5 premium each." },
    ],
    faqs: [
      { q: "What food cost percentage should pizza restaurants target?", a: "Pizza restaurants can achieve some of the lowest food costs in the industry: 22–30% (70–78% gross margin). Dough, sauce, and cheese are inexpensive at scale. A well-run pizza operation targets 25–28% food cost, leaving strong margins to cover labor and rent." },
      { q: "How do pizza restaurants handle delivery pricing?", a: "Most pizza restaurants run dual pricing: in-store prices and delivery prices 15–25% higher. This is increasingly accepted by consumers. Be transparent — list your delivery prices clearly on the app rather than hiding the markup." },
      { q: "How do I price specialty vs. classic pizzas?", a: "Classic pizzas (Margherita, Pepperoni) should be priced at 74–78% margin to attract customers. Specialty pizzas (truffle, seafood) can be priced at 70–72% margin — they cost more but customers expect a premium and the higher absolute price covers it." },
    ],
  },

  "cafe": {
    slug: "cafe",
    name: "Café",
    nameFull: "Café and Coffee Shop",
    tagline: "Smart menu pricing for cafés and coffee shops",
    targetMargin: 72,
    foodCostPct: 28,
    marginRange: "70–80%",
    avgCheckSize: "$7–$14 per person",
    keyChallenge: "Maximizing revenue per seat-hour with high-margin beverages and fast table turns",
    dishes: [
      { name: "Flat White", cost: 0.65, price: 5, margin: 87 },
      { name: "Cold Brew (12oz)", cost: 0.7, price: 5.5, margin: 87 },
      { name: "Avocado Toast", cost: 2.8, price: 11, margin: 75 },
      { name: "Eggs Benedict", cost: 3.5, price: 13, margin: 73 },
      { name: "Açaí Bowl", cost: 3.2, price: 12, margin: 73 },
    ],
    tips: [
      { title: "Coffee is your highest-ROI item — price it confidently", desc: "A flat white at $5 with $0.65 COGS delivers 87% gross margin. Raising it to $5.50 is a 10% revenue increase with zero cost increase. Specialty coffee customers are less price-sensitive than you think." },
      { title: "Push food attachment at POS", desc: "A customer buying a $5 latte is already spending. A prompted 'Would you like a pastry with that?' captures 15–25% of customers for an incremental $3–$6 at 75%+ margin. Train every barista on this." },
      { title: "Merchandise high-margin items visibly", desc: "Retail bags of your coffee beans ($18–$24 at 65% margin) and branded merchandise near the counter capture impulse purchases from loyal customers." },
      { title: "Seasonal drinks justify premium pricing", desc: "A seasonal pumpkin spice or holiday drinks priced $1–$2 above your standard menu creates urgency and novelty. Seasonal specials drive 20–30% higher purchase rates when promoted correctly." },
    ],
    faqs: [
      { q: "What is a good profit margin for a coffee shop?", a: "Coffee and espresso drinks achieve 80–90% gross margin on ingredients. Overall café gross margin (including food) typically runs 65–75%. Net profit for cafés is 6–15% after labor, rent, and equipment costs. The key metric is revenue per labor hour." },
      { q: "How should cafés price specialty coffee vs. drip coffee?", a: "Drip coffee at $2.50–$3.50 acts as a traffic driver and loyalty builder. Specialty espresso drinks at $4.50–$6.50 are your margin drivers. Maintain at least a $2 price gap between drip and specialty to guide customers toward higher-margin choices." },
      { q: "How do I price café food items vs. a bakery?", a: "Café food items should match local bakery/café competitors within 10–15%. If nearby competitors charge $10 for avocado toast, you can charge $10–$11.50 with a quality differentiation story. Café guests anchor food prices to nearby options." },
    ],
  },

  "sushi": {
    slug: "sushi",
    name: "Sushi Restaurant",
    nameFull: "Sushi Restaurant",
    tagline: "Menu pricing strategy for sushi and Japanese restaurants",
    targetMargin: 70,
    foodCostPct: 30,
    marginRange: "68–75%",
    avgCheckSize: "$35–$65 per person",
    keyChallenge: "Managing high fish cost volatility while maintaining competitive pricing",
    dishes: [
      { name: "Salmon Nigiri (2pc)", cost: 2.8, price: 9, margin: 69 },
      { name: "Dragon Roll (8pc)", cost: 5.5, price: 18, margin: 69 },
      { name: "Omakase Set (7 courses)", cost: 28, price: 95, margin: 71 },
      { name: "Edamame", cost: 0.6, price: 5, margin: 88 },
      { name: "Miso Soup", cost: 0.4, price: 3.5, margin: 89 },
    ],
    tips: [
      { title: "Price nigiri by the piece, not by pair", desc: "Listing nigiri as 'per piece' rather than 'per pair' allows finer price control and makes expensive fish like toro and uni feel accessible at $7–$12/piece." },
      { title: "Omakase is your highest-margin format", desc: "Chef's choice menus let you use the entire fish and reduce waste. A $95 omakase at 28% food cost generates $68 gross profit vs. $18 from an individual roll." },
      { title: "Anchor with high-margin starters", desc: "Edamame, miso soup, and gyoza at 80–90% margin set the spending pace. Guests who order starters spend 35–45% more overall." },
      { title: "Review fish prices weekly", desc: "Bluefin tuna, salmon, and sea urchin prices swing 15–30% seasonally. Build a monthly repricing process for your nigiri and sashimi sections." },
    ],
    faqs: [
      { q: "What food cost percentage should sushi restaurants target?", a: "Sushi restaurants typically target 28–35% food cost. High-quality fish at market prices can push food cost to 32–38% for premium cuts. Offset this with high-margin appetizers, drinks, and desserts to keep blended food cost below 32%." },
      { q: "How do I price a sushi roll vs. nigiri?", a: "Rolls use more rice, nori, and fillings but less premium fish per serving — target 68–72% margin. Nigiri is almost pure fish — target 65–70% margin for standard cuts, 62–65% for premium (toro, uni, wagyu). Use rice and vegetable rolls to anchor your menu at accessible price points." },
      { q: "Should sushi restaurants charge more for delivery?", a: "Yes — sushi quality degrades on delivery (soggy rice, separated rolls). Price delivery 20–25% higher and offer fewer items. Many sushi restaurants restrict delivery to rolls only and exclude nigiri and sashimi to protect quality perception." },
    ],
  },

  "mexican": {
    slug: "mexican",
    name: "Mexican Restaurant",
    nameFull: "Mexican Restaurant",
    tagline: "Menu pricing for Mexican and Tex-Mex restaurants",
    targetMargin: 71,
    foodCostPct: 29,
    marginRange: "68–74%",
    avgCheckSize: "$14–$28 per person",
    keyChallenge: "Competing on value in a crowded category while protecting margins on protein-heavy dishes",
    dishes: [
      { name: "Street Tacos (3pc)", cost: 3.2, price: 12, margin: 73 },
      { name: "Burrito Bowl", cost: 4.0, price: 14, margin: 71 },
      { name: "Enchiladas (3pc)", cost: 3.5, price: 13, margin: 73 },
      { name: "Guacamole & Chips", cost: 1.4, price: 8, margin: 83 },
      { name: "Margarita (house)", cost: 0.9, price: 10, margin: 91 },
    ],
    tips: [
      { title: "Guacamole is your highest-margin item — feature it", desc: "Fresh guacamole at $8 with $1.40 COGS delivers 83% margin. Make it tableside for theater. Guests who order guac spend 22% more and rate their experience higher." },
      { title: "Alcohol is your profit engine", desc: "A margarita at $10 with $0.90 COGS is 91% margin. Build a strong cocktail and beer program — beverage mix should target 25–30% of revenue to keep blended food cost healthy." },
      { title: "Price proteins transparently", desc: "Charge $2–$3 for premium proteins (shrimp, steak, carnitas) as add-ons. Guests understand the upgrade and your chicken base price stays competitive." },
      { title: "Combo meals drive volume", desc: "A two-taco + rice + beans combo at $13 with 70% margin drives higher ticket than à la carte ordering. Combos increase perceived value while protecting per-meal margin." },
    ],
    faqs: [
      { q: "What is the typical food cost for a Mexican restaurant?", a: "Mexican restaurants target 28–33% food cost. Rice, beans, tortillas, and salsas are low-cost staples. Protein costs (beef, shrimp) are the main variable — keep protein portions controlled and offer upgrades for premium cuts." },
      { q: "How do I price margaritas and cocktails?", a: "Standard margaritas should be priced at 85–90% margin. Craft margaritas with premium tequila at $14–$18 can still achieve 80%+ margin. Alcohol pricing is your biggest profit opportunity — don't underprice it to seem competitive." },
      { q: "How should Mexican restaurants price delivery?", a: "Add 18–22% to delivery prices. Tacos and burritos travel well, making Mexican food one of the strongest delivery categories. Chips and guac are delivery-risky (soggy) — consider excluding or pricing them higher to offset the quality risk." },
    ],
  },

  "italian": {
    slug: "italian",
    name: "Italian Restaurant",
    nameFull: "Italian Restaurant",
    tagline: "Menu pricing for Italian and pasta restaurants",
    targetMargin: 72,
    foodCostPct: 28,
    marginRange: "70–76%",
    avgCheckSize: "$25–$55 per person",
    keyChallenge: "Positioning fresh pasta and quality ingredients against low-price Italian chain competition",
    dishes: [
      { name: "Cacio e Pepe (fresh pasta)", cost: 2.2, price: 18, margin: 88 },
      { name: "Osso Buco", cost: 9.5, price: 34, margin: 72 },
      { name: "Margherita Pizza (12\")", cost: 3.0, price: 16, margin: 81 },
      { name: "Burrata Starter", cost: 3.5, price: 14, margin: 75 },
      { name: "Tiramisu", cost: 1.8, price: 9, margin: 80 },
    ],
    tips: [
      { title: "Fresh pasta is your highest-margin story", desc: "Housemade pasta costs $1.50–$2.50 in ingredients but commands $18–$28 on the menu — 85–90% gross margin. Prominently feature 'housemade' in your menu descriptions and train staff to tell the story." },
      { title: "Wine is essential to Italian profitability", desc: "Italian restaurants with strong wine programs achieve 65–70% beverage margin. A $48 bottle of Chianti at $14 wholesale is 71% margin. Pair wine with dish recommendations to increase attachment." },
      { title: "Portion size consistency protects margins", desc: "A 10% over-portion on fresh pasta across 50 covers a day adds $18–$25 in daily food cost. Use a kitchen scale and standardize portions by weight." },
      { title: "Desserts are pure margin", desc: "Tiramisu at $9 with $1.80 cost is 80% margin. Make desserts in-house, describe them compellingly, and have staff present them at the table rather than just listing them on a menu." },
    ],
    faqs: [
      { q: "What food cost percentage do Italian restaurants target?", a: "Italian restaurants typically target 26–32% food cost. Fresh pasta and pizza dough have very low ingredient costs (18–25% food cost). Meat and seafood mains run higher (32–38%). The key is a menu that blends high-margin pasta with moderate-margin proteins." },
      { q: "How do I price fresh pasta vs. dried pasta?", a: "Fresh pasta costs 2–3x more than dried ($2 vs. $0.60 per portion) but commands 20–30% higher menu prices. If you're making pasta in-house, price it at $16–$28 depending on your market. Guests understand and expect the premium for housemade." },
      { q: "Should Italian restaurants offer lunch pricing?", a: "Yes — lunch pricing at 70–80% of dinner prices drives volume during off-peak hours. A $22 dinner pasta becomes a $16–$17 lunch portion. Smaller portions, faster service, and lower labor cost make lunch profitable even at reduced prices." },
    ],
  },

  "burger": {
    slug: "burger",
    name: "Burger Restaurant",
    nameFull: "Burger Restaurant",
    tagline: "Menu pricing for burger joints and smash burger concepts",
    targetMargin: 70,
    foodCostPct: 30,
    marginRange: "67–74%",
    avgCheckSize: "$12–$22 per person",
    keyChallenge: "Standing out vs. fast food chains on quality while keeping prices accessible",
    dishes: [
      { name: "Classic Smash Burger", cost: 3.5, price: 12, margin: 71 },
      { name: "Bacon Cheeseburger (double)", cost: 5.2, price: 16, margin: 68 },
      { name: "Crispy Chicken Sandwich", cost: 3.8, price: 13, margin: 71 },
      { name: "Loaded Fries", cost: 1.5, price: 7, margin: 79 },
      { name: "Milkshake", cost: 1.2, price: 7, margin: 83 },
    ],
    tips: [
      { title: "Fries and shakes are your profit anchor", desc: "Fries at 75–82% margin and milkshakes at 80–85% margin subsidize your burgers. A combo meal (burger + fries + drink) at $18 with 70% blended margin outperforms individual burger sales." },
      { title: "Beef quality is a price signal — use it", desc: "100% fresh beef, never frozen, or a specific farm or breed (Wagyu, Angus) lets you price 20–30% above standard fast casual. Communicate the sourcing story everywhere — menu, signage, social." },
      { title: "Smash burgers have better unit economics", desc: "A smash burger uses 2–3oz per patty vs. 5–6oz for a classic. At the same menu price, smash burger concepts achieve 5–8% lower food cost — a significant margin advantage at volume." },
      { title: "Price premium toppings as add-ons", desc: "Bacon ($1.50), fried egg ($1), avocado ($2), and specialty sauces ($0.50) at 80%+ margin increase average ticket by $3–$5 without increasing kitchen complexity." },
    ],
    faqs: [
      { q: "What is the food cost percentage for a burger restaurant?", a: "Burger restaurants typically target 28–33% food cost. Ground beef is your largest variable cost — price volatility can swing 10–20% seasonally. Many operators lock in beef prices with 30-day supplier contracts to stabilize food cost." },
      { q: "How do I price a premium burger vs. a value burger?", a: "Anchor your menu with a value burger at $10–$12 to attract first-time customers. Price your signature premium burger at $16–$22 to showcase quality and drive 25–30% higher check. The value burger draws them in; the premium burger is where you make margin." },
      { q: "How do burger restaurants compete with McDonald's on price?", a: "Don't try to. Compete on quality, freshness, and experience — not price. A $14 smash burger with fresh beef and house-made sauce competes with $22 sit-down restaurant burgers, not a $6 fast food burger. Position up, not down." },
    ],
  },

  "bbq": {
    slug: "bbq",
    name: "BBQ Restaurant",
    nameFull: "BBQ Restaurant",
    tagline: "Pricing strategy for BBQ and smokehouse restaurants",
    targetMargin: 68,
    foodCostPct: 32,
    marginRange: "65–72%",
    avgCheckSize: "$18–$35 per person",
    keyChallenge: "Managing expensive, long-cook proteins and volatile meat prices",
    dishes: [
      { name: "Brisket (1/2 lb)", cost: 5.5, price: 16, margin: 66 },
      { name: "Pulled Pork Sandwich", cost: 3.8, price: 13, margin: 71 },
      { name: "Baby Back Ribs (full rack)", cost: 12, price: 38, margin: 68 },
      { name: "Mac & Cheese (side)", cost: 0.9, price: 5, margin: 82 },
      { name: "Coleslaw (side)", cost: 0.5, price: 4, margin: 88 },
    ],
    tips: [
      { title: "Sides are your highest-margin products", desc: "Mac and cheese, coleslaw, baked beans, and cornbread run 80–90% gross margin. A 3-meat plate with 3 sides at $32 achieves better blended margin than the meat alone at $28. Always push sides." },
      { title: "Price by weight for premium cuts", desc: "Brisket and ribs priced per pound or per piece protects you against weight variation in yield. A smoked brisket with 35% cooking loss needs weight-based pricing to maintain margin consistency." },
      { title: "Combo plates drive volume and margin", desc: "A 2-meat combo with 2 sides at $22–$28 increases attachment and check size. Bundle your 3 most popular meats with popular sides to simplify ordering and improve kitchen efficiency." },
      { title: "Sell by the pound for catering and takeout", desc: "BBQ travels well and is highly cateringable. Bulk takeout pricing (brisket $22/lb, pulled pork $16/lb) at 55–60% margin is lower than dine-in but volume compensates. Require 24-hour advance notice." },
    ],
    faqs: [
      { q: "What food cost should BBQ restaurants target?", a: "BBQ restaurants typically run 30–38% food cost — higher than most restaurant categories due to expensive proteins and significant cooking shrinkage (brisket loses 30–40% weight during smoking). Target 32–35% and offset with high-margin sides and drinks." },
      { q: "How do I account for cooking shrinkage in BBQ pricing?", a: "Buy weight vs. serve weight is critical. A 14lb raw brisket at $8/lb costs $112 and yields 8–9lb after smoking — $12.50–$14/lb serve cost. Price per pound on the menu at $18–$22 to achieve 65–70% gross margin after shrinkage." },
      { q: "How should BBQ restaurants price catering?", a: "BBQ catering typically prices per person ($18–$35/person depending on protein selection) or per pound. Minimum orders ($300–$500 food minimum) are essential for profitability. Include setup, serving equipment, and travel as separate line items." },
    ],
  },

  "seafood": {
    slug: "seafood",
    name: "Seafood Restaurant",
    nameFull: "Seafood Restaurant",
    tagline: "Menu pricing for seafood and fish restaurants",
    targetMargin: 68,
    foodCostPct: 32,
    marginRange: "65–73%",
    avgCheckSize: "$35–$70 per person",
    keyChallenge: "Managing extreme protein cost volatility and waste from perishable inventory",
    dishes: [
      { name: "Grilled Salmon Fillet", cost: 8, price: 28, margin: 71 },
      { name: "Lobster Bisque", cost: 4.5, price: 16, margin: 72 },
      { name: "Fish & Chips", cost: 5.5, price: 19, margin: 71 },
      { name: "Shrimp Cocktail", cost: 4.0, price: 16, margin: 75 },
      { name: "Clam Chowder (cup)", cost: 1.8, price: 9, margin: 80 },
    ],
    tips: [
      { title: "Use market price for premium catches", desc: "Seasonal and premium fish (halibut, Dover sole, bluefin) should be listed as 'market price' — this protects margin when costs spike and signals exclusivity. Train staff to quote the current price confidently." },
      { title: "Chowder and bisques are margin anchors", desc: "Soups at 78–85% margin are among your most profitable items. Feature house-made clam chowder or lobster bisque as a signature to attract guests and boost average ticket with a $9–$14 first course." },
      { title: "Order fresh daily to minimize waste", desc: "Seafood waste is profit loss. Order 90–95% of expected daily volume and run specials to move inventory that won't last another day. A 'catch of the day' special eliminates waste and creates excitement." },
      { title: "Wine pairings increase check size significantly", desc: "A recommended white wine or champagne pairing at $12–$18/glass increases average ticket by 25–35%. Train front-of-house to suggest pairings naturally — 'Our halibut pairs beautifully with the Sancerre tonight.'" },
    ],
    faqs: [
      { q: "What food cost percentage do seafood restaurants target?", a: "Seafood restaurants typically target 30–38% food cost — higher than most categories because premium fish is expensive and perishable. Many operate at 35% food cost but compensate with higher menu prices and strong beverage programs." },
      { q: "How do I price lobster on my menu?", a: "Live lobster pricing should be market-based or reviewed weekly. A 1.5lb lobster at $22/lb wholesale costs $33 before prep — price at $65–$85 on the menu depending on your market and service style. This is 50–60% food cost, justified by the premium experience." },
      { q: "How do seafood restaurants reduce waste?", a: "Order daily based on previous day sales plus 10–15% buffer. Use trim and less-popular cuts for chowders, tacos, or staff meals. Freeze-eligible fish (salmon, tuna) can be purchased in larger quantities. Waste should be tracked daily." },
    ],
  },

  "steakhouse": {
    slug: "steakhouse",
    name: "Steakhouse",
    nameFull: "Steakhouse",
    tagline: "Premium menu pricing for steakhouses and chophouses",
    targetMargin: 68,
    foodCostPct: 32,
    marginRange: "65–72%",
    avgCheckSize: "$60–$120 per person",
    keyChallenge: "Justifying premium beef prices and managing high protein food costs",
    dishes: [
      { name: "8oz Filet Mignon", cost: 18, price: 58, margin: 69 },
      { name: "16oz Ribeye", cost: 22, price: 72, margin: 69 },
      { name: "Wedge Salad", cost: 2.5, price: 14, margin: 82 },
      { name: "Lobster Mac & Cheese (side)", cost: 6, price: 22, margin: 73 },
      { name: "Crème Brûlée", cost: 2.2, price: 12, margin: 82 },
    ],
    tips: [
      { title: "Add-ons and upgrades are essential profitability levers", desc: "Compound butter ($3), sauce ($4), and Oscar-style topping ($14) at 80%+ margin each are pure profit. A $58 filet with $20 in add-ons at 82% margin generates more incremental profit than the steak itself." },
      { title: "Sides are priced independently — and expensively", desc: "Steakhouse sides at $10–$22 each are industry standard. Guests expect à la carte sides and the 80%+ margins on truffle fries, creamed spinach, and lobster mac are critical to steakhouse economics." },
      { title: "Wine is your biggest revenue opportunity", desc: "A steakhouse with a curated wine list achieves 65–70% beverage margin. Premium steaks and wine are naturally paired — train staff to lead with recommendations. A $120 bottle of Cabernet at $35 wholesale is 71% margin." },
      { title: "Grade transparency justifies price premiums", desc: "USDA Prime, Wagyu, or dry-aged designations justify 30–50% price premiums. Guests at steakhouses read menus carefully — detailed beef sourcing descriptions increase willingness to pay significantly." },
    ],
    faqs: [
      { q: "What food cost percentage do steakhouses target?", a: "Steakhouses typically run 30–38% food cost — among the highest in the restaurant industry due to expensive beef cuts. They compensate with very high menu prices ($50–$150 per entrée), strong wine programs, and high-margin sides and add-ons." },
      { q: "How do I price Wagyu vs. USDA Prime beef?", a: "American Wagyu (A5-grade) wholesale runs $50–$80/lb — price it at $120–$200+ on the menu. USDA Prime wholesale at $25–$35/lb should be priced at $60–$95 on the menu. Both achieve 65–70% food cost but at very different absolute margins per cover." },
      { q: "How do steakhouses handle dry-aged beef pricing?", a: "Dry-aged beef has 20–30% additional shrinkage and aging costs — factor this into your buy weight calculation. A 45-day dry-aged bone-in ribeye at $35/lb wholesale with 25% shrinkage has an effective cost of $46/lb. Price at $90–$120 on the menu." },
    ],
  },

  "indian": {
    slug: "indian",
    name: "Indian Restaurant",
    nameFull: "Indian Restaurant",
    tagline: "Menu pricing for Indian and South Asian restaurants",
    targetMargin: 72,
    foodCostPct: 28,
    marginRange: "70–76%",
    avgCheckSize: "$18–$35 per person",
    keyChallenge: "Competing on value while justifying premium positioning for quality spices and slow-cooked dishes",
    dishes: [
      { name: "Chicken Tikka Masala", cost: 3.8, price: 16, margin: 76 },
      { name: "Lamb Biryani", cost: 5.5, price: 19, margin: 71 },
      { name: "Butter Chicken", cost: 3.5, price: 15, margin: 77 },
      { name: "Garlic Naan (2pc)", cost: 0.5, price: 4, margin: 88 },
      { name: "Mango Lassi", cost: 0.8, price: 5.5, margin: 85 },
    ],
    tips: [
      { title: "Bread is your highest-margin product", desc: "Naan, roti, and paratha at 85–90% gross margin are among the cheapest to make and most frequently ordered. Always suggest bread with curry dishes — bread attachment adds $3–$5 to every table at near-zero cost." },
      { title: "Spice blends are a profit-protecting moat", desc: "Your unique masala and spice combinations are impossible to replicate at home. Emphasize your 'house blend' and slow-cooking times — this differentiates you from fast-casual competitors and justifies a 15–20% premium." },
      { title: "Lunch buffets drive volume with lower food cost", desc: "Buffets at $14–$19/person let you use par-cooked curries and reduce waste. Food cost runs 32–38% for buffets — offset with high beverage sales and large group volume during the lunch rush." },
      { title: "Vegetarian dishes are your most profitable", desc: "Dal, palak paneer, and chana masala at $12–$14 with $1.50–$2.50 ingredient costs are 80–85% gross margin. Feature vegetarian dishes prominently — they're appealing, profitable, and increasingly sought by health-conscious diners." },
    ],
    faqs: [
      { q: "What food cost percentage should Indian restaurants target?", a: "Indian restaurants typically target 26–32% food cost. Rice, lentils, and bread are inexpensive ingredients. Protein dishes (lamb, shrimp) run higher (35–40% food cost) but are offset by vegetarian dishes at 15–20% food cost. Target a blended 28–30%." },
      { q: "How do I price a lunch buffet vs. dinner à la carte?", a: "Lunch buffet: $14–$19/person with 33–38% food cost and fast table turns. Dinner à la carte: $18–$35/person with 26–30% food cost and higher gross margin per cover. Both formats work — buffet drives traffic, à la carte drives margin." },
      { q: "How should Indian restaurants price delivery?", a: "Indian food travels well — curries actually improve after 15–20 minutes. Add 15–20% to delivery prices. Exclude easily damaged items like tandoori items. Biryani, curries, and dal are your best delivery products and hold quality for 30–45 minutes." },
    ],
  },

  "thai": {
    slug: "thai",
    name: "Thai Restaurant",
    nameFull: "Thai Restaurant",
    tagline: "Menu pricing for Thai and Southeast Asian restaurants",
    targetMargin: 72,
    foodCostPct: 28,
    marginRange: "69–75%",
    avgCheckSize: "$16–$30 per person",
    keyChallenge: "Managing imported ingredient costs (fish sauce, lemongrass, Thai basil) while staying price-competitive",
    dishes: [
      { name: "Pad Thai (shrimp)", cost: 3.5, price: 14, margin: 75 },
      { name: "Green Curry (chicken)", cost: 3.2, price: 14, margin: 77 },
      { name: "Tom Yum Soup", cost: 2.8, price: 12, margin: 77 },
      { name: "Spring Rolls (4pc)", cost: 1.5, price: 8, margin: 81 },
      { name: "Mango Sticky Rice", cost: 1.8, price: 8, margin: 78 },
    ],
    tips: [
      { title: "Noodle and rice dishes are your backbone — price them confidently", desc: "Pad Thai, fried rice, and noodle dishes at $12–$16 with 72–78% margin are what most guests order. These are your volume drivers. Don't undercut them to compete — focus on quality and authenticity." },
      { title: "Spice level customization adds perceived value", desc: "Offering 1–5 spice levels costs nothing but increases guest satisfaction and repeat visits. Guests who get exactly the spice they want return 40% more frequently. Make your spice scale descriptive, not just numerical." },
      { title: "Appetizers increase check size significantly", desc: "Spring rolls, satay, and soups at 78–85% margin add $6–$12 to the table when ordered. Train staff to suggest 'we recommend starting with our Tom Yum — it's our most popular starter.'" },
      { title: "Desserts are an opportunity most Thai restaurants miss", desc: "Mango sticky rice, fried banana, and coconut ice cream at 75–82% margin are easy to make, culturally authentic, and highly instagrammable. Feature them with photos and suggest them after the main." },
    ],
    faqs: [
      { q: "What is a good food cost for a Thai restaurant?", a: "Thai restaurants typically target 27–33% food cost. Rice and noodles are inexpensive staples. Proteins (shrimp, beef) run higher. Some imported Thai ingredients (makrut lime leaves, galangal) command premium prices — factor sourcing costs into your recipes." },
      { q: "How do I price Thai curry vs. noodle dishes?", a: "Thai curries and noodle dishes are typically priced similarly ($12–$16) despite curries sometimes costing slightly more to make. Price by category (appetizer/main/dessert) and let your ingredient variations average out rather than pricing each dish individually." },
      { q: "Should Thai restaurants offer family-style or individual pricing?", a: "Individual portions are easier to cost and manage. Family-style encourages ordering more dishes and increases table spend by 20–30% — but requires larger portions and more prep. Family-style works well for larger groups (4+); individual for pairs and solo diners." },
    ],
  },

  "chinese": {
    slug: "chinese",
    name: "Chinese Restaurant",
    nameFull: "Chinese Restaurant",
    tagline: "Menu pricing for Chinese and dim sum restaurants",
    targetMargin: 70,
    foodCostPct: 30,
    marginRange: "67–74%",
    avgCheckSize: "$16–$35 per person",
    keyChallenge: "Pricing family-style dishes fairly while managing large menus and food cost across hundreds of items",
    dishes: [
      { name: "Kung Pao Chicken", cost: 3.5, price: 14, margin: 75 },
      { name: "Peking Duck (half)", cost: 14, price: 45, margin: 69 },
      { name: "Dim Sum (3pc basket)", cost: 1.5, price: 6, margin: 75 },
      { name: "Fried Rice (large)", cost: 1.8, price: 9, margin: 80 },
      { name: "Hot & Sour Soup", cost: 1.2, price: 6, margin: 80 },
    ],
    tips: [
      { title: "Family-style ordering increases per-person spend", desc: "A table of 4 ordering 4–6 shared dishes at $12–$18 each generates $48–$72 per person at the table — higher than individual ordering. Train staff to suggest 'one dish per person plus one extra for sharing.'" },
      { title: "Rice and soup are high-margin fillers", desc: "Steamed rice at $2–$3 per person and soups at $6–$9 with 78–85% margin should be actively suggested, not left to guests to request. They fill the table and protect overall food cost." },
      { title: "Reduce menu size to improve quality and margins", desc: "Chinese restaurants often carry 80–120+ items, creating waste and inconsistency. Cutting to 40–60 focused items reduces inventory, food waste, and training burden — and typically improves margins by 3–5%." },
      { title: "Price banquet and large-group menus at premium", desc: "Set menus for 8–10 person tables at $38–$65/person with 28–30% food cost generate strong gross profit. Feature banquet packages prominently — they provide guaranteed revenue and simplify kitchen operations." },
    ],
    faqs: [
      { q: "What food cost percentage should Chinese restaurants target?", a: "Chinese restaurants typically target 28–35% food cost. Vegetables, tofu, and rice-based dishes run very low (18–22% food cost). Seafood and premium proteins (abalone, shark fin alternatives) run 38–45%. The blended average across a typical Chinese menu falls at 28–32%." },
      { q: "How do I price a Peking duck?", a: "Peking duck requires significant prep time (24–48 hours) and yields 55–65% of raw weight after roasting. A 5lb duck at $12/lb wholesale costs $60 before prep and yields a 3.25lb roasted duck. Price a full duck at $85–$110, half at $45–$60, to achieve 65–70% gross margin." },
      { q: "How should Chinese restaurants price dim sum?", a: "Dim sum is traditionally priced by basket size: small (2–3pc, $5–$7), medium (3–4pc, $7–$10), large (3–4pc, $10–$14). Dumplings, har gow, and siu mai should be $5–$8 per basket at 72–80% margin. Premium items (xiao long bao, turnip cake) can be priced $1–$2 higher." },
    ],
  },

  "vegan": {
    slug: "vegan",
    name: "Vegan Restaurant",
    nameFull: "Vegan and Plant-Based Restaurant",
    tagline: "Menu pricing for vegan and plant-based restaurants",
    targetMargin: 72,
    foodCostPct: 28,
    marginRange: "69–76%",
    avgCheckSize: "$16–$30 per person",
    keyChallenge: "Overcoming price perception ('vegan food should be cheap') while covering premium ingredient costs",
    dishes: [
      { name: "Jackfruit BBQ Bowl", cost: 3.2, price: 14, margin: 77 },
      { name: "Mushroom Wellington", cost: 5.5, price: 22, margin: 75 },
      { name: "Cashew Cheese Pizza", cost: 3.8, price: 16, margin: 76 },
      { name: "Açaí Bowl", cost: 3.0, price: 12, margin: 75 },
      { name: "Cold Press Juice", cost: 1.5, price: 9, margin: 83 },
    ],
    tips: [
      { title: "Premium plant-based proteins justify premium prices", desc: "Jackfruit, tempeh, seitan, and cashew cheese cost more than their animal counterparts. Don't apologize for it — emphasize the craftsmanship, sourcing, and nutrition. Vegan diners are accustomed to premium pricing for quality alternatives." },
      { title: "Beverages are your margin engine", desc: "Cold-press juices, superfood smoothies, and ceremonial matcha at 80–90% margin are uniquely suited to the vegan audience. Build a strong beverage program — it's where you recover margin from premium ingredient costs." },
      { title: "Communicate your sourcing story", desc: "Organic, local, and ethically sourced ingredients justify 15–25% price premiums to conscious consumers. Your sourcing story is a marketing asset — feature it on your menu, signage, and social media." },
      { title: "Position against health outcomes, not against meat", desc: "Price comparisons against meat dishes backfire. Instead, price against the wellness and experience value: a $22 mushroom Wellington is an experience comparable to any fine dining entrée, not a substitution for a steak." },
    ],
    faqs: [
      { q: "Why do vegan restaurants charge high prices?", a: "Premium plant-based proteins (jackfruit, cashew cheese, beyond meat), organic produce, and specialty ingredients cost more than conventional alternatives. Additionally, vegan dishes often require more preparation time. A $16 vegan bowl reflects real ingredient and labor costs — not a markup for the category." },
      { q: "What food cost percentage should vegan restaurants target?", a: "Vegan restaurants typically target 27–33% food cost. Whole vegetables and grains are low-cost, but premium specialty ingredients (nuts, superfoods, plant-based proteins) raise average food cost. Beverages at 15–20% food cost help bring the blended average down." },
      { q: "How do I price vegan dishes vs. omnivore menu items?", a: "Price based on your cost + target margin, not based on what a comparable meat dish costs elsewhere. A vegan dish that costs $4.50 to make at 30% food cost should be $15 — regardless of what a chicken dish costs nearby. Your guests are choosing you for values and quality, not to find the cheapest option." },
    ],
  },

  "breakfast": {
    slug: "breakfast",
    name: "Breakfast & Brunch",
    nameFull: "Breakfast and Brunch Restaurant",
    tagline: "Menu pricing for breakfast and brunch restaurants",
    targetMargin: 70,
    foodCostPct: 30,
    marginRange: "67–74%",
    avgCheckSize: "$14–$25 per person",
    keyChallenge: "Maximizing revenue in limited operating hours with high egg and dairy cost volatility",
    dishes: [
      { name: "Eggs Benedict", cost: 3.8, price: 14, margin: 73 },
      { name: "Avocado Toast (with egg)", cost: 3.2, price: 13, margin: 75 },
      { name: "Pancake Stack (3pc)", cost: 1.5, price: 10, margin: 85 },
      { name: "Breakfast Burrito", cost: 3.0, price: 12, margin: 75 },
      { name: "Mimosa (bottomless)", cost: 2.5, price: 18, margin: 86 },
    ],
    tips: [
      { title: "Brunch cocktails are your highest-margin product", desc: "Bottomless mimosas at $18 with $2.50 cost in prosecco and OJ deliver 86% gross margin. Bloody Marys, espresso martinis, and house cocktails at 85%+ margin are the fastest path to improving blended food cost at brunch." },
      { title: "Pancakes and pastries anchor your menu profitably", desc: "Pancakes at 82–88% margin are among your most profitable dishes. Feature them prominently. Every table that orders pancakes improves your blended food cost and makes expensive egg and protein dishes more viable." },
      { title: "Weekend brunch is a revenue opportunity — price accordingly", desc: "Weekend brunch guests spend 20–30% more than weekday breakfast guests. Weekend-specific pricing ($1–$2 premium) on popular items is accepted and expected. Use weekend brunch to test premium menu items." },
      { title: "Egg prices are your biggest cost variable — track weekly", desc: "Egg prices swing 30–50% seasonally and dramatically with supply disruptions. Review your breakfast food cost monthly. Items with 4+ eggs (frittatas, egg plates) need to be repriced when egg costs spike." },
    ],
    faqs: [
      { q: "What food cost percentage should breakfast restaurants target?", a: "Breakfast restaurants typically target 28–35% food cost. Eggs, dairy, and proteins (bacon, sausage) are the main cost drivers. Pancakes, pastries, and toast run 12–18% food cost. Coffee and beverages at 15–20% food cost help bring the blended average down." },
      { q: "How do I price avocado toast profitably?", a: "Avocado toast with egg at $3–$3.50 in ingredients should be priced at $12–$14 for 73–76% gross margin. The dish is not overpriced at $13 — avocado cost alone runs $1.50–$2 per portion, and guests understand and accept the price for quality." },
      { q: "Should breakfast restaurants offer bottomless drinks?", a: "Bottomless coffee is expected and builds loyalty — offer it as a standard table experience. Bottomless brunch cocktails ($18–$24/person) are highly profitable at 83–88% margin. Set a 90-minute table limit and ensure there's enough food to balance alcohol consumption." },
    ],
  },

  "sandwich": {
    slug: "sandwich",
    name: "Sandwich Shop",
    nameFull: "Sandwich Shop and Deli",
    tagline: "Menu pricing for sandwich shops and delis",
    targetMargin: 68,
    foodCostPct: 32,
    marginRange: "65–72%",
    avgCheckSize: "$10–$18 per person",
    keyChallenge: "Competing with Subway and Jimmy John's on price while differentiating on quality",
    dishes: [
      { name: "Turkey Club (12\")", cost: 4.2, price: 13, margin: 68 },
      { name: "Italian Sub (12\")", cost: 3.8, price: 12, margin: 68 },
      { name: "Grilled Cheese (premium)", cost: 2.5, price: 10, margin: 75 },
      { name: "Cup of Soup", cost: 1.0, price: 5, margin: 80 },
      { name: "Chips + Drink Combo", cost: 1.2, price: 4, margin: 70 },
    ],
    tips: [
      { title: "Soup is your highest-margin product — feature it every day", desc: "Housemade soup at $1/portion and $5–$7 selling price is 82–85% gross margin. A 'sandwich + soup' combo at $14 beats selling the sandwich alone and increases food cost percentage favorably." },
      { title: "Premium bread is a price signal", desc: "Brioche, ciabatta, focaccia, and sourdough justify $1–$2 price premiums per sandwich. Bread cost is 15–20% of sandwich cost — premium bread costs $0.30–$0.60 more but lets you charge $1.50–$2 more." },
      { title: "Combo upgrades are pure margin", desc: "A 'make it a combo' upsell (chips + drink) at $3.50 with $1.20 cost is 66% margin and increases ticket size by 27–35%. Train every staff member to offer it with every sandwich order." },
      { title: "Catering orders are high-volume, high-margin", desc: "Office lunch catering ($12–$18/person) with guaranteed volume and simplified menu reduces waste and labor complexity. Box lunches with sandwich + side + drink are easy to execute and highly profitable at 65–70% margin." },
    ],
    faqs: [
      { q: "What food cost should sandwich shops target?", a: "Sandwich shops typically target 30–36% food cost. Deli meats (turkey, roast beef, salami) are your most expensive ingredients. Vegetables, condiments, and bread are low-cost. Control protein portions carefully — a 1oz overpour on deli meat across 100 sandwiches is $8–$15 in lost margin daily." },
      { q: "How do I price a sandwich to compete with Subway?", a: "Don't compete on price — compete on quality. A 12-inch premium sandwich at $12–$14 targets a completely different customer than a $8 Subway footlong. Your customer is choosing quality, freshness, and craft. Price for that customer." },
      { q: "How do I price sandwiches by the half?", a: "Half sandwiches should be priced at 65–70% of the full price (not 50%). A $13 full sandwich has fixed costs (bread, packaging, labor) that don't halve. Half at $9–$9.50 is standard and customers understand." },
    ],
  },

  "salad": {
    slug: "salad",
    name: "Salad Bar & Bowl Concept",
    nameFull: "Salad Bar and Bowl Restaurant",
    tagline: "Menu pricing for salad bars and healthy bowl concepts",
    targetMargin: 71,
    foodCostPct: 29,
    marginRange: "68–75%",
    avgCheckSize: "$12–$18 per person",
    keyChallenge: "Managing fresh produce waste and competing on value vs. grocery salad bars",
    dishes: [
      { name: "Build-Your-Own Salad (lg)", cost: 3.5, price: 13, margin: 73 },
      { name: "Grain Bowl (quinoa base)", cost: 3.2, price: 13, margin: 75 },
      { name: "Protein Add-On (chicken)", cost: 1.8, price: 4, margin: 55 },
      { name: "Fresh-Pressed Juice", cost: 1.8, price: 9, margin: 80 },
      { name: "House Dressing (2oz)", cost: 0.3, price: 1.5, margin: 80 },
    ],
    tips: [
      { title: "Protein add-ons drive revenue — price them right", desc: "Chicken, salmon, and tofu add-ons at $3–$5 should achieve 55–65% margin (lower than your base, but still profitable). Guests who add protein spend 30–40% more and are more satisfied with their experience." },
      { title: "Beverages rescue your food cost percentage", desc: "Fresh-pressed juices, kombucha, and specialty drinks at 78–85% margin bring your blended food cost down significantly. Build a beverage program that matches your healthy positioning." },
      { title: "Batch cook grains to reduce waste", desc: "Quinoa, farro, and brown rice can be cooked in large batches and held 3–4 days refrigerated. This reduces daily waste by 15–20% and speeds service. Calculate your expected daily portions before ordering." },
      { title: "Dressings are a profit opportunity often overlooked", desc: "Housemade dressings at $0.25–$0.40/2oz portion sold at $1.50 are 75–85% margin. Offer bottled house dressing to take home at $8–$10 — it's 60%+ margin and creates a brand touchpoint outside your restaurant." },
    ],
    faqs: [
      { q: "What food cost percentage do salad restaurants target?", a: "Salad and bowl concepts typically target 27–33% food cost. Fresh produce is relatively inexpensive but highly perishable — waste management is critical. Proteins are your most expensive ingredient. Target 30% blended food cost across your full menu including beverages." },
      { q: "How do I price a build-your-own salad?", a: "Flat pricing ($12–$14 for any combination) is simpler for customers and easier to manage than by-ingredient pricing. Caps on high-cost ingredients (proteins, nuts, premium cheese) protect margins. Most guests build $3.50–$4.50 food cost salads at a $13 price point." },
      { q: "How do salad concepts compete with grocery salad bars?", a: "Compete on freshness, quality, and experience — not price. A $13 restaurant salad with made-to-order assembly, quality ingredients, and the service experience is a different product than a grocery bar. Customers who choose you have already decided not to go to the grocery." },
    ],
  },
};

export const ALL_TYPES = Object.values(RESTAURANT_TYPES);
