import { MetadataRoute } from "next";
import { ALL_DISHES } from "./how-to-price/[dish]/data";
import { ALL_COUNTRIES } from "./restaurant-pricing/[country]/data";

const RESTAURANT_TYPES = [
  "fine-dining", "fast-casual", "food-truck", "bakery", "pizza", "cafe",
  "burger", "sushi", "mexican", "italian", "chinese", "thai", "indian",
  "bbq", "seafood", "steakhouse", "sandwich", "salad", "vegan", "breakfast",
];

export default function sitemap(): MetadataRoute.Sitemap {
  const base = "https://www.aimenupricer.com";
  return [
    { url: base, lastModified: new Date(), changeFrequency: "weekly", priority: 1 },
    { url: `${base}/pricing`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    // Calculators — highest SEO priority
    { url: `${base}/food-cost-calculator`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.95 },
    { url: `${base}/recipe-cost-calculator`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.95 },
    { url: `${base}/menu-cost-calculator`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/restaurant-markup-calculator`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/restaurant-profit-calculator`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/bakery-pricing-calculator`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/catering-pricing-calculator`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/coffee-shop-pricing-calculator`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/food-truck-pricing-calculator`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/delivery-platform-calculator`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/prime-cost-calculator`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/labor-cost-calculator`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/break-even-calculator`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/portion-cost-calculator`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/cocktail-pricing-calculator`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    // About & Compare
    { url: `${base}/about`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/editorial-policy`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/compare`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/compare/menupricer-vs-spreadsheet`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/compare/menupricer-vs-square`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/compare/menupricer-vs-toast`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    // Blog
    { url: `${base}/blog`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.8 },
    { url: `${base}/blog/how-to-price-a-restaurant-menu`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/food-cost-formula`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/restaurant-profit-margin`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/delivery-platform-commission`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/recipe-yield`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/how-to-cost-a-dish`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/how-to-raise-menu-prices`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/food-cost-percentage-by-restaurant-type`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/menu-engineering`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/how-to-write-menu-descriptions`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/catering-pricing-guide`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/bakery-pricing-guide`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/coffee-shop-menu-pricing`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/restaurant-menu-design-tips`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/compare/menupricer-vs-menutotal`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/compare/menupricer-vs-craftable`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/blog/food-cost-percentage-calculator`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/what-is-yield-in-cooking`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/ghost-kitchen-pricing`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/par-level-restaurant`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/corkage-fee`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/service-charge-vs-tip`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/food-costing-template`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/prime-cost-restaurant`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/restaurant-profit-loss-statement`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/catering-cost-per-person`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/food-truck-startup-costs`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/how-to-start-a-catering-business`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/restaurant-bookkeeping`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/restaurant-seasonality`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/cost-to-open-a-restaurant`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/restaurant-kpis`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/restaurant-budget-template`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/restaurant-inventory-costing-methods`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/restaurant-failure-rate`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/recipe-costing-without-recipes`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/blog/markup-vs-margin`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/menu-pricing-mistakes`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/how-often-to-reprice-menu`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/portion-control-food-cost`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/supplier-price-increases`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/why-chatgpt-cant-price-your-menu`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/how-to-price-a-menu-before-opening`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/food-truck-event-pricing`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/meal-prep-business-pricing`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/catering-quote-template`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/cake-pricing-guide`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    // Alternatives — high commercial intent
    { url: `${base}/alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/alternatives/marketman-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/alternatives/marginedge-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    // Free tools hub & glossary
    { url: `${base}/tools`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/glossary`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    // How to price [dish] — programmatic SEO
    { url: `${base}/how-to-price`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    ...ALL_DISHES.map((d) => ({
      url: `${base}/how-to-price/${d.slug}`,
      lastModified: new Date(),
      changeFrequency: "monthly" as const,
      priority: 0.8,
    })),
    // Restaurant pricing by country
    { url: `${base}/restaurant-pricing`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    ...ALL_COUNTRIES.map((c) => ({
      url: `${base}/restaurant-pricing/${c.slug}`,
      lastModified: new Date(),
      changeFrequency: "monthly" as const,
      priority: 0.8,
    })),
    // Industry pages
    { url: `${base}/menu-pricing`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    ...RESTAURANT_TYPES.map((t) => ({
      url: `${base}/menu-pricing/${t}`,
      lastModified: new Date(),
      changeFrequency: "monthly" as const,
      priority: 0.7,
    })),
  ];
}
