import { jsPDF } from "jspdf";
import { MenuItem } from "./menuStore";
import { calcMargin } from "./calculations";
import { BrandConfig } from "./brandConfig";

export function exportMenuPdf(items: MenuItem[], brand?: BrandConfig) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const W = 210;
  const margin = 18;
  const orange = [249, 115, 22] as const;
  const gray8 = [31, 31, 31] as const;
  const gray5 = [107, 114, 128] as const;
  const gray2 = [229, 231, 235] as const;
  const amber = [245, 158, 11] as const;

  const restName = brand?.restaurantName?.trim();
  const tagline = brand?.tagline?.trim();

  // Header
  doc.setFillColor(...orange);
  doc.rect(0, 0, W, restName ? 32 : 28, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(restName ? 16 : 18);
  doc.setTextColor(255, 255, 255);
  doc.text(restName || "MenuPricer", margin, restName ? 12 : 13);
  if (restName) {
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.text(tagline || "Menu Pricing Report", margin, 20);
    doc.text(new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }), W - margin, 20, { align: "right" });
    doc.setFontSize(7);
    doc.setTextColor(255, 200, 150);
    doc.text("Generated by MenuPricer · aimenupricer.com", W - margin, 29, { align: "right" });
  } else {
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.text("Full Menu Pricing Report", margin, 20);
    doc.text(new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }), W - margin, 20, { align: "right" });
  }

  let y = restName ? 40 : 36;

  // Summary stats
  const avgMargin = items.reduce((sum, item) => {
    const std = item.tiers[1] ?? item.tiers[0];
    return sum + (std ? calcMargin(std.price, item.totalCost) : 0);
  }, 0) / items.length;

  const statBoxes = [
    { label: "Total Dishes", value: String(items.length) },
    { label: "Avg. Margin (Standard)", value: `${avgMargin.toFixed(0)}%` },
    { label: "Generated", value: new Date().toLocaleDateString("en-US", { month: "short", day: "numeric" }) },
  ];
  const bw = (W - margin * 2) / 3 - 3;
  statBoxes.forEach((b, i) => {
    const bx = margin + i * (bw + 4.5);
    doc.setFillColor(255, 247, 237);
    doc.roundedRect(bx, y, bw, 16, 2, 2, "F");
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(...gray5);
    doc.text(b.label, bx + bw / 2, y + 5.5, { align: "center" });
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(...orange);
    doc.text(b.value, bx + bw / 2, y + 12.5, { align: "center" });
  });
  y += 24;

  // Group items by category
  const grouped: Record<string, MenuItem[]> = {};
  for (const item of items) {
    const cat = item.category?.trim() || "Uncategorized";
    if (!grouped[cat]) grouped[cat] = [];
    grouped[cat].push(item);
  }

  const hasCategories = Object.keys(grouped).length > 1 || !grouped["Uncategorized"];

  for (const [cat, catItems] of Object.entries(grouped)) {
    // Category header
    if (hasCategories) {
      if (y > 260) { doc.addPage(); y = 20; }
      doc.setFillColor(31, 31, 31);
      doc.rect(margin, y, W - margin * 2, 8, "F");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8);
      doc.setTextColor(255, 255, 255);
      doc.text(cat.toUpperCase(), margin + 4, y + 5.5);
      y += 13;
    }

    catItems.forEach((item) => {
      if (y > 230) { doc.addPage(); y = 20; }

      doc.setFillColor(255, 247, 237);
      doc.roundedRect(margin, y, W - margin * 2, 10, 2, 2, "F");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(...orange);
      doc.text(item.dishName, margin + 4, y + 7);
      if (item.totalCost > 0) {
        doc.setFont("helvetica", "normal");
        doc.setFontSize(8);
        doc.setTextColor(...gray5);
        doc.text(`Cost: $${item.totalCost.toFixed(2)}`, W - margin - 4, y + 7, { align: "right" });
      }
      y += 13;

      const tierW = (W - margin * 2) / 3 - 2;
      const tierColors: [number, number, number][] = [[200, 200, 200], [...orange] as [number, number, number], [...amber] as [number, number, number]];
      item.tiers.forEach((tier, i) => {
        const tx = margin + i * (tierW + 3);
        const tc = tierColors[i] ?? tierColors[0];
        const m2 = item.totalCost > 0 ? calcMargin(tier.price, item.totalCost) : tier.margin;

        doc.setDrawColor(...tc);
        doc.setLineWidth(0.4);
        doc.roundedRect(tx, y, tierW, 22, 2, 2, "S");

        doc.setFont("helvetica", "bold");
        doc.setFontSize(7.5);
        doc.setTextColor(...gray5);
        doc.text(tier.name, tx + tierW / 2, y + 6, { align: "center" });

        doc.setFont("helvetica", "bold");
        doc.setFontSize(12);
        doc.setTextColor(...gray8);
        doc.text(`$${tier.price.toFixed(2)}`, tx + tierW / 2, y + 13, { align: "center" });

        doc.setFont("helvetica", "normal");
        doc.setFontSize(7.5);
        doc.setTextColor(...orange);
        doc.text(`Margin ${m2.toFixed(0)}%`, tx + tierW / 2, y + 19, { align: "center" });
      });
      y += 27;

      doc.setDrawColor(...gray2);
      doc.setLineWidth(0.2);
      doc.line(margin, y, W - margin, y);
      y += 6;
    });
  }

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let p = 1; p <= pageCount; p++) {
    doc.setPage(p);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(...gray5);
    doc.text("Generated by MenuPricer · aimenupricer.com", margin, 290);
    doc.text(`Page ${p} / ${pageCount}`, W - margin, 290, { align: "right" });
  }

  doc.save(`menu_pricing_${Date.now()}.pdf`);
}
