import { jsPDF } from "jspdf";
import { MenuItem } from "./menuStore";
import { calcMargin } from "./calculations";

export function exportMenuPdf(items: MenuItem[]) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const W = 210;
  const margin = 18;
  const orange = [249, 115, 22] as const;
  const gray8 = [31, 31, 31] as const;
  const gray5 = [107, 114, 128] as const;
  const gray2 = [229, 231, 235] as const;
  const amber = [245, 158, 11] as const;

  // Header
  doc.setFillColor(...orange);
  doc.rect(0, 0, W, 28, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(255, 255, 255);
  doc.text("MenuPricer", margin, 13);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text("Full Menu Pricing Report", margin, 20);
  doc.text(new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }), W - margin, 20, { align: "right" });

  let y = 36;

  // Summary stats
  const avgMargin = items.reduce((sum, item) => {
    const std = item.tiers[1] ?? item.tiers[0];
    return sum + (std ? calcMargin(std.price, item.totalCost) : 0);
  }, 0) / items.length;

  const statBoxes = [
    { label: "Total Dishes", value: String(items.length) },
    { label: "Avg. Margin (Standard)", value: `${avgMargin.toFixed(0)}%` },
    { label: "Generated", value: new Date().toLocaleDateString("en-US", { month: "short", day: "numeric" }) },
  ];
  const bw = (W - margin * 2) / 3 - 3;
  statBoxes.forEach((b, i) => {
    const bx = margin + i * (bw + 4.5);
    doc.setFillColor(255, 247, 237);
    doc.roundedRect(bx, y, bw, 16, 2, 2, "F");
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(...gray5);
    doc.text(b.label, bx + bw / 2, y + 5.5, { align: "center" });
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(...orange);
    doc.text(b.value, bx + bw / 2, y + 12.5, { align: "center" });
  });
  y += 24;

  // Each dish
  items.forEach((item) => {
    // Page break check (need ~60mm per dish)
    if (y > 230) { doc.addPage(); y = 20; }

    // Dish name row
    doc.setFillColor(255, 247, 237);
    doc.roundedRect(margin, y, W - margin * 2, 10, 2, 2, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(...orange);
    doc.text(item.dishName, margin + 4, y + 7);
    if (item.totalCost > 0) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(...gray5);
      doc.text(`Cost: $${item.totalCost.toFixed(2)}`, W - margin - 4, y + 7, { align: "right" });
    }
    y += 13;

    // Tier columns
    const tierW = (W - margin * 2) / 3 - 2;
    const tierColors: [number, number, number][] = [[200, 200, 200], ...([orange, amber])];
    item.tiers.forEach((tier, i) => {
      const tx = margin + i * (tierW + 3);
      const tc = tierColors[i] ?? tierColors[0];
      const margin2 = item.totalCost > 0 ? calcMargin(tier.price, item.totalCost) : tier.margin;

      doc.setDrawColor(...tc);
      doc.setLineWidth(0.4);
      doc.roundedRect(tx, y, tierW, 22, 2, 2, "S");

      // Tier name
      doc.setFont("helvetica", "bold");
      doc.setFontSize(7.5);
      doc.setTextColor(...gray5);
      doc.text(tier.name, tx + tierW / 2, y + 6, { align: "center" });

      // Price
      doc.setFont("helvetica", "bold");
      doc.setFontSize(12);
      doc.setTextColor(...gray8);
      doc.text(`$${tier.price.toFixed(2)}`, tx + tierW / 2, y + 13, { align: "center" });

      // Margin
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7.5);
      doc.setTextColor(...orange);
      doc.text(`Margin ${margin2.toFixed(0)}%`, tx + tierW / 2, y + 19, { align: "center" });
    });
    y += 27;

    // Divider
    doc.setDrawColor(...gray2);
    doc.setLineWidth(0.2);
    doc.line(margin, y, W - margin, y);
    y += 6;
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let p = 1; p <= pageCount; p++) {
    doc.setPage(p);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(...gray5);
    doc.text("Generated by MenuPricer · menupricer.app", margin, 290);
    doc.text(`Page ${p} / ${pageCount}`, W - margin, 290, { align: "right" });
  }

  doc.save(`menu_pricing_${Date.now()}.pdf`);
}
