import { jsPDF } from "jspdf";

export function exportPricingPdf(opts: {
  dishName: string;
  totalCost: number;
  ingredientCost: number;
  breakdown: string;
  aiContent: string;
}) {
  const { dishName, totalCost, ingredientCost, breakdown, aiContent } = opts;
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const W = 210;
  const margin = 18;
  const contentW = W - margin * 2;
  let y = 0;

  const orange = [249, 115, 22] as const;
  const gray8 = [31, 31, 31] as const;
  const gray5 = [107, 114, 128] as const;
  const gray2 = [229, 231, 235] as const;

  // Header band
  doc.setFillColor(...orange);
  doc.rect(0, 0, W, 28, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(255, 255, 255);
  doc.text("MenuPricer", margin, 13);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text("AI Menu Pricing Report", margin, 20);
  doc.text(new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }), W - margin, 20, { align: "right" });

  y = 38;

  // Dish name
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(...gray8);
  doc.text(dishName, margin, y);
  y += 10;

  // Divider
  doc.setDrawColor(...gray2);
  doc.setLineWidth(0.3);
  doc.line(margin, y, W - margin, y);
  y += 7;

  // Cost summary boxes
  const boxes = [
    { label: "Ingredient Cost", value: `$${ingredientCost.toFixed(2)}` },
    { label: "Total Cost (incl. labor)", value: `$${totalCost.toFixed(2)}` },
    { label: "Est. Gross Margin", value: `${((1 - totalCost / (totalCost * 3)) * 100).toFixed(0)}%` },
  ];
  const boxW = contentW / 3 - 3;
  boxes.forEach((b, i) => {
    const bx = margin + i * (boxW + 4.5);
    doc.setFillColor(255, 247, 237);
    doc.roundedRect(bx, y, boxW, 18, 2, 2, "F");
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(...gray5);
    doc.text(b.label, bx + boxW / 2, y + 6, { align: "center" });
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(...orange);
    doc.text(b.value, bx + boxW / 2, y + 14, { align: "center" });
  });
  y += 25;

  // Ingredient breakdown
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(...gray8);
  doc.text("Ingredient Breakdown", margin, y);
  y += 5;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(...gray5);
  const bkLines = breakdown.split(";").map(s => s.trim()).filter(Boolean);
  bkLines.forEach(line => {
    if (y > 265) { doc.addPage(); y = 20; }
    doc.text(`• ${line}`, margin + 2, y);
    y += 5;
  });
  y += 4;

  // Divider
  doc.setDrawColor(...gray2);
  doc.line(margin, y, W - margin, y);
  y += 7;

  // AI Content
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(...gray8);
  doc.text("AI Pricing Analysis", margin, y);
  y += 6;

  const aiLines = aiContent.split("\n");
  for (const raw of aiLines) {
    if (y > 270) { doc.addPage(); y = 20; }
    const line = raw.trim();
    if (!line) { y += 2; continue; }

    if (line.startsWith("## ")) {
      y += 2;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(...orange);
      doc.text(line.replace("## ", ""), margin, y);
      y += 6;
    } else if (line.startsWith("**") && line.endsWith("**")) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(...gray8);
      doc.text(line.replace(/\*\*/g, ""), margin + 2, y);
      y += 5;
    } else {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.5);
      doc.setTextColor(...gray5);
      const wrapped = doc.splitTextToSize(line, contentW - 4);
      wrapped.forEach((wl: string) => {
        if (y > 270) { doc.addPage(); y = 20; }
        doc.text(wl, margin + 2, y);
        y += 4.5;
      });
    }
  }

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let p = 1; p <= pageCount; p++) {
    doc.setPage(p);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(...gray5);
    doc.text("Generated by MenuPricer · menupricer.app", margin, 290);
    doc.text(`Page ${p} / ${pageCount}`, W - margin, 290, { align: "right" });
  }

  doc.save(`${dishName.replace(/[^a-z0-9]/gi, "_")}_pricing.pdf`);
}
